### ISSUE TITLE
No second controller

### ISSUE THREAD

**Issue by dirkk0** [konaraddio/web-riimote#2]
Hi,

  awesome project, thanks!

The hand icon with the number one on it seems to imply that you can pair other mobile devices ('wii style'). But this is not the case, unless I did something wrong?

Best,
  Dirk

**Comment by konaraddi** [comment]
Only one controller is supported at the moment. I can see why the number on the cursor icon can be misleading; I should've gone with a plain icon.

**Comment by konaraddi** [comment]
I'm closing this issue because the goal of this project was to show that a smartphone can turn into a 3D controller with a web app and the goal has been accomplished. There are no plans for further development of this project.
