### ISSUE TITLE
JS error on IceCat

### ISSUE THREAD

**Issue by emberdart** [konaraddio/web-riimote#4]
IceCat complains about JS not running,
because it's blocked it,
because it thinks it's closed source,
because it hasn't got a JS Web Labels manifest.
See: https://www.gnu.org/software/librejs/free-your-javascript.html

**Comment by konaraddi** [comment]
The goal of this project was to show that a smartphone can turn into a 3D controller with a web app. This goal has been accomplished and the project works best in Chrome. So there are no plans to support other browsers like IceCat. But feel free to fork it!
